on:
  push:
    branches: [main]

jobs: 
  grade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: '0'
    - name: Setup Python
      if: always()
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.6
    - name: Install requirements
      run: |
        cd src
        pip install -r requirements.txt
    - name: Publish page
      run: |
        python vector.py
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
